### ISSUE TITLE
Error in instanton example

### ISSUE THREAD

**Issue by changwmyung** [i-pi/i-pi#144]
I tried running the example at examples/pes/instanton/ch4h-cbe-rate/reactant/phonons/ and I encounter an error as below: 

Exception in thread Thread-400:
Traceback (most recent call last):
  File "/home/cwm31/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/cwm31/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cwm31/prog/i-pi/ipi/engine/motion/phonons.py", line 115, in step
    self.printall(self.prefix, self.refdynmatrix.copy(), fixdof=self.fixdof)
  File "/home/cwm31/prog/i-pi/ipi/engine/motion/phonons.py", line 129, in printall
    mask = np.delete(np.arange(3 * self.beads.natoms), fixdof)
  File "<__array_function__ internals>", line 5, in delete
  File "/home/cwm31/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by litman90** [comment]
Thanks for reporting.
This is indeed a small bug in the phonon subroutine.
I've created a PR with the corresponding bugfix (see PR #145 ), you can try it now but it will be soon merged into master.

**Comment by venkatkapil24** [comment]
fixed
