### ISSUE TITLE
Cannot run a single particle simualtion with `pile_g` thermostat

### ISSUE THREAD

**Issue by zc62** [i-pi/i-pi#193]
Hi, I am trying to test out TRPMD, and I suppose I should be using the `pile_g` thermostat for the simulation to be a TRPMD simualtion. I tried the harmonic oscillator example, but the degree of freedom got subtracted by 3, therefore there is no dof remaining, causing errors. While other thermostats like `langevin` works fine, but I think with `langevin` the simulation is not TRPMD anymore (am I right?).

Here are input files that I use:
`init.xyz`:
```
1

H   0.000   0.000   0.000
```

`input.langevin.xml`:
```xml
<simulation verbosity='high'>
  <output prefix='simulation.langevin'>
    <properties stride='100' filename='out'>  [ step, time{picosecond}, conserved{kelvin}, temperature{kelvin}, kinetic_cv{kelvin}, potential{kelvin}, pressure_cv{megapascal}] </properties>
    <checkpoint filename='restart' stride='2000' />
    <trajectory filename='xc' stride='2' format='xyz' cell_units='angstrom'> x_centroid{angstrom} </trajectory>
    <trajectory filename='vc' stride='2' cell_units='angstrom'> v_centroid </trajectory>
    <trajectory filename='for' stride='2000' format='xyz' cell_units='angstrom'> forces </trajectory>
    <trajectory filename='pos' stride='2000' cell_units='angstrom'>positions{angstrom}</trajectory>
  </output>
  <total_steps>1000</total_steps>
  <prng>
    <seed>31415</seed>
  </prng>
  <ffsocket mode='unix' name='driver'>
    <address>localhost</address>
  </ffsocket>
  <system>
    <initialize nbeads='4'>
      <cell mode='abc'>
        [   15., 15.0, 15.0 ]
      </cell>
      <file mode='xyz'> init.xyz </file>
      <velocities mode='thermal' units='kelvin'>300</velocities>
    </initialize>
    <forces>
      <force forcefield='driver'/>
    </forces>
    <ensemble>
      <temperature units='kelvin'>300</temperature>
    </ensemble>
    <motion mode='dynamics'>
      <dynamics mode='nvt'>
        <thermostat mode='langevin'>
          <tau units='femtosecond'>1000</tau>
          <pile_lambda> 0.5 </pile_lambda>
        </thermostat>
        <timestep units='femtosecond'>0.5</timestep>
      </dynamics>
    </motion>
  </system>
</simulation>
```

`input.pile_g.xml`:
```xml
<simulation verbosity='high'>
  <output prefix='simulation.pile_g'>
    <properties stride='100' filename='out'>  [ step, time{picosecond}, conserved{kelvin}, temperature{kelvin}, kinetic_cv{kelvin}, potential{kelvin}, pressure_cv{megapascal}] </properties>
    <checkpoint filename='restart' stride='2000' />
    <trajectory filename='xc' stride='2' format='xyz' cell_units='angstrom'> x_centroid{angstrom} </trajectory>
    <trajectory filename='vc' stride='2' cell_units='angstrom'> v_centroid </trajectory>
    <trajectory filename='for' stride='2000' format='xyz' cell_units='angstrom'> forces </trajectory>
    <trajectory filename='pos' stride='2000' cell_units='angstrom'>positions{angstrom}</trajectory>
  </output>
  <total_steps>1000</total_steps>
  <prng>
    <seed>31415</seed>
  </prng>
  <ffsocket mode='unix' name='driver'>
    <address>localhost</address>
  </ffsocket>
  <system>
    <initialize nbeads='4'>
      <cell mode='abc'>
        [   15., 15.0, 15.0 ]
      </cell>
      <file mode='xyz'> init.xyz </file>
      <velocities mode='thermal' units='kelvin'>300</velocities>
    </initialize>
    <forces>
      <force forcefield='driver'/>
    </forces>
    <ensemble>
      <temperature units='kelvin'>300</temperature>
    </ensemble>
    <motion mode='dynamics'>
      <dynamics mode='nvt'>
        <thermostat mode='pile_g'>
          <tau units='femtosecond'>1000</tau>
          <pile_lambda> 0.5 </pile_lambda>
        </thermostat>
        <timestep units='femtosecond'>0.5</timestep>
      </dynamics>
    </motion>
  </system>
</simulation>
```
The only differences are thermostat and prefix.

and the Makefile to run the simulation (I use the Fortran driver):
```makefile
.PHONY: all clean harmonic
all: harmonic

driver:=i-pi-driver
IPI:=i-pi

define run_driver
  for i in `seq 1 $1`; do \
    $(driver) -u -h localhost -m harm3d -o 0.016257 & \
  done;
endef
-include make.in

harmonic:
	$(IPI) input.langevin.xml & sleep 5; \
	$(call run_driver,4) \
	wait
	$(IPI) input.pile_g.xml & sleep 5; \
	$(call run_driver,4) \
	wait

clean:
	rm -f *simulation.* RESTART EXIT
```

Here is the error for the `pile_g` run, which won't happen with `langevin`:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xxx/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxx/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/i-pi/ipi/engine/motion/dynamics.py", line 246, in step
    self.integrator.step(step)
  File "/home/xxx/i-pi/ipi/engine/motion/dynamics.py", line 526, in step
    self.tstep()
  File "/home/xxx/i-pi/ipi/engine/motion/dynamics.py", line 519, in tstep
    self.thermostat.step()
  File "/home/xxx/i-pi/ipi/engine/thermostats.py", line 408, in step
    t.step()
  File "/home/xxx/i-pi/ipi/engine/thermostats.py", line 473, in step
    rg = 2.0 * self.prng.gamma((self.ndof - 2) / 2) + self.prng.g ** 2
  File "/home/xxx/i-pi/ipi/utils/prng.py", line 104, in gamma
    return self.rng.gamma(k, theta)
  File "mtrand.pyx", line 1665, in numpy.random.mtrand.RandomState.gamma
  File "_common.pyx", line 553, in numpy.random._common.cont
  File "_common.pyx", line 366, in numpy.random._common.check_constraint
ValueError: shape < 0
```

There is another thing I don't know if worthy a new issue. I saw the CPU usage of i-PI is pretty low. Spawning 16 clients on a 16 core node uses only 1 hour CPU time after 4 hours real life time has passed, and I do feel it is slow for just a simple harmonic oscillator simulation. Any suggestions about what can be wrong in my setup?

**Comment by ceriottm** [comment]
So, several considerations here.
1) you should make sure to run with `<fixcom>False</fixcom>` as an option to <motion> 
2) the point of pile_g is only to have small disturbance on the centroid. a pile_l with a very large tau (of the order of 1e10 times the period) would do as fine
3) you can play with `<latency>` as an option to ffsocket. Consider that the point of i-PI is not to run the harmonic oscillator, but high-cost forcefields or ab inition MD so we never optimized it to run with a cheapo potential

**Comment by zc62** [comment]
`<fixcom>False</fixcom>` indeed works, thx!
