### ISSUE TITLE
i-PI not working with ASE

### ISSUE THREAD

**Issue by shwetaresearchsite** [i-pi/i-pi#265]
Hi,

 i-pi with fhi-aims via ase client is not working. Please help!

```
Traceback (most recent call last):
  File "/home/md/molecular-dynamics-with-i-pi-main/Tutorial/Exercise-1/exercise/new/run_aimd.py", line 33, in <module>
    client = SocketClient(unixsocket="paramganga")
  File "/home/ase/venv/lib/python3.10/site-packages/ase-3.22.1-py3.10.egg/ase/calculators/socketio.py", line 422, in __init__
    sock.connect(actualsocket)
FileNotFoundError: [Errno 2] No such file or directory


```
Thanks!

**Comment by shwetaresearchsite** [comment]
@eszterpos Kindly help!

**Comment by mahrossi** [comment]
Hi @shwetaresearchsite , do you still have this error or did it go away? That seemed like a problem with the name of the socket.

**Comment by ceriottm** [comment]
Closing this as it seems that it was a problem of setup more than a bug
